package movies;

import java.util.Arrays;

public class MoviesArray {
    public static Movie[] findAll() {
        return new Movie[]{
                new Movie("\tCitizen Kane", "drama"),
                new Movie("\tCasablanca", "drama"),
                new Movie("\tThe Godfather", "drama"),
                new Movie("\tGone With The Wind", "drama"),
                new Movie("\tLawrence Of Arabia", "drama"),
                new Movie("\tThe Wizard Of Oz", "musical"),
                new Movie("\tThe Graduate", "drama"),
                new Movie("\tOn The Waterfront", "drama"),
                new Movie("\tSchindler's List", "drama"),
                new Movie("\tSingin' In The Rain", "musical"),
                new Movie("\tIt's A Wonderful Life", "drama"),
                new Movie("\tSunset Boulevard", "drama"),
                new Movie("\tThe Bridge On The River Kwai", "drama"),
                new Movie("\tSome Like It Hot", "drama"),
                new Movie("\tStar Wars", "scifi"),
                new Movie("\tAll About Eve", "drama"),
                new Movie("\tThe African Queen", "drama"),
                new Movie("\tPsycho" , "horror"),
                new Movie("\tChinatown", "drama"),
                new Movie("\tOne Flew Over The Cuckoo's Nest", "drama"),
                new Movie("\tThe Grapes Of Wrath", "drama"),
                new Movie("\t2001: A Space Odyssey", "scifi"),
                new Movie("\tThe Maltese Falcon", "drama"),
                new Movie("\tRaging Bull", "drama"),
                new Movie("\tE.T. The extra-terrestrial", "scifi"),
                new Movie("\tDr. Strangelove", "drama"),
                new Movie("\tBonnie And Clyde", "drama"),
                new Movie("\tApocalypse Now", "drama"),
                new Movie("\tMr. Smith Goes to Washington", "drama"),
                new Movie("\tThe Treasure Of The Sierra Madre", "drama"),
                new Movie("\tAnnie Hall", "comedy"),
                new Movie("\tThe Godfather Part II", "drama"),
                new Movie("\tHigh Noon", "drama"),
                new Movie("\tTo Kill A Mockingbird", "drama"),
                new Movie("\tIt Happened One Night", "drama"),
                new Movie("\tMidnight Cowboy", "drama"),
                new Movie("\tThe Best Years Of Our Lives", "drama"),
                new Movie("\tDouble Indemnity", "drama"),
                new Movie("\tDoctor Zhivago", "drama"),
                new Movie("\tNorth By Northwest", "drama"),
                new Movie("\tWest Side Story", "musical"),
                new Movie("\tRear Window", "drama"),
                new Movie("\tKing Kong", "horror"),
                new Movie("\tThe Birth Of A Nation", "drama"),
                new Movie("\tA Streetcar Named Desire", "drama"),
                new Movie("\tA Clockwork Orange", "scifi"),
                new Movie("\tTaxi Driver", "drama"),
                new Movie("\tJaws", "horror"),
                new Movie("\tSnow White And The Seven Dwarfs", "animated"),
                new Movie("\tButch Cassidy And The Sundance Kid", "drama"),
                new Movie("\tThe Philadelphia Story", "drama"),
                new Movie("\tFrom Here To Eternity", "drama"),
                new Movie("\tAmadeus", "drama"),
                new Movie("\tAll Quiet On The Western Front", "drama"),
                new Movie("\tThe Sound Of Music", "musical"),
                new Movie("\tM*A*S*H", "comedy"),
                new Movie("\tThe Third Man", "drama"),
                new Movie("\tFantasia", "animated"),
                new Movie("\tRebel Without A Cause", "drama"),
                new Movie("\tRaiders Of The Lost Ark", "drama"),
                new Movie("\tVertigo", "drama"),
                new Movie("\tTootsie", "comedy"),
                new Movie("\tStagecoach", "drama"),
                new Movie("\tClose Encounters Of The Third Kind", "scifi"),
                new Movie("\tThe Silence Of The Lambs", "horror"),
                new Movie("\tNetwork", "drama"),
                new Movie("\tThe Manchurian Candidate", "drama"),
                new Movie("\tAn American In Paris", "drama"),
                new Movie("\tShane", "drama"),
                new Movie("\tThe French Connection", "drama"),
                new Movie("\tForrest Gump", "drama"),
                new Movie("\tBen-Hur", "drama"),
                new Movie("\tWuthering Heights", "drama"),
                new Movie("\tThe Gold Rush", "drama"),
                new Movie("\tDances With Wolves", "drama"),
                new Movie("\tCity Lights", "drama"),
                new Movie("\tAmerican Graffiti", "drama"),
                new Movie("\tRocky", "drama"),
                new Movie("\tThe Deer Hunter", "drama"),
                new Movie("\tThe Wild Bunch", "drama"),
                new Movie("\tModern Times", "drama"),
                new Movie("\tGiant", "drama"),
                new Movie("\tPlatoon", "drama"),
                new Movie("\tFargo", "drama"),
                new Movie("\tDuck Soup", "comedy"),
                new Movie("\tMutiny On The Bounty", "drama"),
                new Movie("\tFrankenstein", "horror"),
                new Movie("\tEasy Rider", "drama"),
                new Movie("\tPatton", "drama"),
                new Movie("\tThe Jazz Singer", "drama"),
                new Movie("\tMy Fair Lady", "musical"),
                new Movie("\tA Place In The Sun", "drama"),
                new Movie("\tThe Apartment", "drama"),
                new Movie("\tGoodfellas", "drama"),
                new Movie("\tPulp Fiction", "drama"),
                new Movie("\tThe Searchers", "drama"),
                new Movie("\tBringing Up Baby", "drama"),
                new Movie("\tUnforgiven", "drama"),
                new Movie("\tGuess Who's Coming To Dinner", "drama"),
                new Movie("\tYankee Doodle Dandy", "musical")
        };
    }
}
